# Generated by Django 5.1 on 2024-08-07 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('added_person', models.CharField(max_length=255)),
                ('added_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
